version: "3.5"

services:
  # Masa CMS Server
  masamysqlcfml:
    build:
      dockerfile: Dockerfile
      target: cf23
    depends_on:
      - masamysql
    env_file: ../.env
    environment:
      MURA_DBTYPE: mysql
      MURA_DBCONNECTIONSTRING: "jdbc:mysql://masamysql:3306/masadb"
      MURA_DBCLASS: com.mysql.cj.jdbc.Driver
      MURA_DBUSERNAME: root
      MURA_DBPASSWORD: rootpassword
      MURA_DBHOST: masamysql
      MURA_DBPORT: 3306
      installModules: debugger,mysql,caching,image,mail,zip
    volumes:
      - ../../masacms:/app
    ports:
      - "80:8500"

  # MySQL
  masamysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: masadb
    volumes:
      - masamysqldata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  masamysqldata:
