services:
  # Masa CMS Server
  masa_mysql_boxlang:
    image: ortussolutions/boxlang:miniserver
    env_file: ../.env
    environment:
      MURA_DBTYPE: mysql
      MURA_DBCONNECTIONSTRING: "jdbc:mysql://masa_mysql:3306/masadb?useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=true"
      MURA_DBCLASS: com.mysql.jdbc.Driver
      MURA_DBUSERNAME: root
      MURA_DBPASSWORD: rootpassword
      MURA_DBHOST: masa_mysql
      MURA_DBPORT: 3306
      MURA_PORT: 18281
      BOXLANG_MODULES: bx-compat-cfml,bx-esapi,bx-image,bx-ini,bx-lsp,bx-mail,bx-password-encrypt,bx-pdf,bx-unsafe-evaluate,bx-wddx,bx-mysql
    networks:
      - masa-test
    volumes:
      - ../../masacms:/app
    ports:
      - "18281:8080"

networks:
  masa-test:
    name: masa-test
    external: true
