services:
  # Masa CMS Server
  masa_mariadb_lucee:
    image: lucee/lucee:latest
    env_file: ../.env
    environment:
      MURA_DBTYPE: mysql
      MURA_DBCONNECTIONSTRING: "jdbc:mysql://masa_mariadb:3306/masadb?useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=true"
      MURA_DBCLASS: com.mysql.jdbc.Driver
      MURA_DBUSERNAME: root
      MURA_DBPASSWORD: rootpassword
      MURA_DBHOST: masa_mariadb
      MURA_DBPORT: 3307
      MURA_PORT: 18180
    networks:
      - masa-test
    volumes:
      - ../../masacms:/var/www
      - ../common/password.txt:/opt/lucee/server/lucee-server/context/password.txt
    ports:
      - "18180:8888"

networks:
  masa-test:
    name: masa-test
    external: true
