FROM adobecoldfusion/coldfusion:latest-2021 as cf21

FROM adobecoldfusion/coldfusion:latest-2023 as cf23

FROM adobecoldfusion/coldfusion:latest-2025 as cf25

FROM adobecoldfusion/coldfusion:latest as latest
