services:
  # MariaDB
  masa_mariadb:
    image: mariadb:latest
    environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: masadb
    networks:
      - masa-test
    volumes:
        - masa_mariadb_data:/var/lib/mysql
    ports:
        - "3307:3306"

volumes:
    masa_mariadb_data:

networks:
  masa-test:
    name: masa-test
    driver: bridge