services:
  # Masa CMS Server
  masa_mariadb_boxlang:
    image: ortussolutions/boxlang:miniserver
    env_file: ../.env
    environment:
      MURA_DBTYPE: mysql
      MURA_DBCONNECTIONSTRING: "jdbc:mysql://masa_mariadb:3306/masadb?useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=true"
      MURA_DBCLASS: com.mysql.jdbc.Driver
      MURA_DBUSERNAME: root
      MURA_DBPASSWORD: rootpassword
      MURA_DBHOST: masa_mariadb
      MURA_DBPORT: 3307
      BOXLANG_MODULES: bx-compat,bx-esapi,bx-mariadb,bx-ini
    networks:
      - masa-test
    volumes:
      - ../../masacms:/app
    ports:
      - "18280:8080"

networks:
  masa-test:
    name: masa-test
    external: true
